version: '3'

services:
  rails:
    container_name: rails
    build: .
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    volumes:
      - .:/home/app/webapp
    ports:
      - "3001:3000"
